### ISSUE TITLE
Restart issue

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-Camect#7]
```
Nov 3, 2021 at 12:54:55 PM
   Camect Debug                    Camect NVR: Camect Event: {u'roi': {u'object': [{u'vehicle_status': 3, u'name': u'truck', u'min_size': 0.0018713248, u'contour': [{u'point': [{u'y': 0.26666668, u'x': 0.375}, {u'y': 0.2888889, u'x': 0.375}, {u'y': 0.2888889, u'x': 0.625}, {u'y': 0.24444444, u'x': 0.625}]}], u'max_size': 0.0027989878, u'movement_trace': {u'point': [{u'y': 0.27753246, u'x': 0.6035452}, {u'y': 0.277978, u'x': 0.5990344}, {u'y': 0.27979082, u'x': 0.5893078}, {u'y': 0.27930814, u'x': 0.5868634}, {u'y': 0.28277546, u'x': 0.58516675}, {u'y': 0.28194013, u'x': 0.5661138}, {u'y': 0.28026778, u'x': 0.55620414}, {u'y': 0.2831092, u'x': 0.5030275}, {u'y': 0.28201383, u'x': 0.48445183}, {u'y': 0.28245932, u'x': 0.48244703}, {u'y': 0.283984, u'x': 0.47886497}, {u'y': 0.28394604, u'x': 0.4625882}, {u'y': 0.28500298, u'x': 0.45393395}, {u'y': 0.28503507, u'x': 0.4479521}, {u'y': 0.2853101, u'x': 0.4411155}, {u'y': 0.28611678, u'x': 0.4332596}, {u'y': 0.28695208, u'x': 0.42950064}, {u'y': 0.2863952, u'x': 0.42423066}, {u'y': 0.288153, u'x': 0.41715324}, {u'y': 0.28854275, u'x': 0.41364563}]}}], u'contour': [{u'point': [{u'y': 0.24444444, u'x': 0.625}, {u'y': 0.26666668, u'x': 0.375}, {u'y': 0.2888889, u'x': 0.375}, {u'y': 0.2888889, u'x': 0.625}]}]}, u'detected_obj': [u'pickup'], u'url': u'https://home.camect.com/home/eb20236a011db606c4957c4a197773a557a5ea26/camera?id=0c4c5c682b8a76e77a08&ts=1635958491831', u'cam_name': u'East_Side', u'cam_id': u'0c4c5c682b8a76e77a08', u'type': u'alert', u'desc': u'East_Side just saw a pickup.'}
   Camect                          Camect NVR: East_Side just saw a pickup.
   Camect Debug                    Alert event: camectID: 451814034, cam_id: 0c4c5c682b8a76e77a08, detected_obj = [u'pickup']

Nov 3, 2021 at 12:56:03 PM
   Camect Warning                  Camect NVR: Restarting Device, error: Connection is already closed.
   Camect                          Camect NVR: Stopping Device
   Trigger                         Camect Offline
   Camect                          Camect NVR: Starting Device
   Camect Debug                    Camect NVR: Camect Status: Disconnected
   Camect Debug                    Camect NVR: Camect Status: Created
   Camect Warning                  Camect NVR: Restarting Device, error: [Errno 8] nodename nor servname provided, or not known
   Camect Debug                    Camect NVR: Camect Status: Disconnected
   Camect Error                    Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1278, in deviceUpdated
  File "plugin.py", line 67, in deviceStartComm
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/Plugins/Camect.indigoPlugin/Contents/Server Plugin/camect.py", line 86, in get_info
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 71, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='camect.local', port=443): Max retries exceeded with url: /api/GetHomeInfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x119c8c690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

   Camect                          Camect NVR: Stopping Device
   Camect                          Camect NVR: Starting Device
   Camect Debug                    Camect NVR: Camect Status: Created
   Camect Warning                  Camect NVR: Restarting Device, error: [Errno 8] nodename nor servname provided, or not known
   Camect Debug                    Camect NVR: Camect Status: Disconnected
   Camect Error                    Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1278, in deviceUpdated
  File "plugin.py", line 67, in deviceStartComm
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/Plugins/Camect.indigoPlugin/Contents/Server Plugin/camect.py", line 86, in get_info
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 71, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='camect.local', port=443): Max retries exceeded with url: /api/GetHomeInfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x119c8c350>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

   Camect                          Camect NVR: Stopping Device
   Camect                          Camect NVR: Starting Device
   Camect Debug                    Camect NVR: Camect Status: Created
   Camect Warning                  Camect NVR: Restarting Device, error: [Errno 8] nodename nor servname provided, or not known
   Camect Debug                    Camect NVR: Camect Status: Disconnected
   Schedule                        Camect Offline (delayed action)
   Camect Error                    Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1278, in deviceUpdated
  File "plugin.py", line 67, in deviceStartComm
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/Plugins/Camect.indigoPlugin/Contents/Server Plugin/camect.py", line 86, in get_info
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 71, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='camect.local', port=443): Max retries exceeded with url: /api/GetHomeInfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x119c19250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

   Camect                          Camect NVR: Stopping Device
   Camect                          Camect NVR: Starting Device
   Camect Debug                    Camect NVR: Camect Status: Created
   Camect Warning                  Camect NVR: Restarting Device, error: [Errno 8] nodename nor servname provided, or not known
   Camect Debug                    Camect NVR: Camect Status: Disconnected
   Camect Error                    Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1278, in deviceUpdated
  File "plugin.py", line 67, in deviceStartComm
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/Plugins/Camect.indigoPlugin/Contents/Server Plugin/camect.py", line 86, in get_info
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 71, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='camect.local', port=443): Max retries exceeded with url: /api/GetHomeInfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x119c19590>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

   Camect                          Camect NVR: Stopping Device
   Camect                          Camect NVR: Starting Device
   Camect Debug                    Camect NVR: Camect Status: Created
   Camect Warning                  Camect NVR: Restarting Device, error: [Errno 8] nodename nor servname provided, or not known
   Camect Debug                    Camect NVR: Camect Status: Disconnected
   Camect Error                    Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1278, in deviceUpdated
  File "plugin.py", line 67, in deviceStartComm
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/Plugins/Camect.indigoPlugin/Contents/Server Plugin/camect.py", line 86, in get_info
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 71, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='camect.local', port=443): Max retries exceeded with url: /api/GetHomeInfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x119c19850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

   Camect                          Camect NVR: Stopping Device
   Camect                          Camect NVR: Starting Device
   Camect Debug                    Camect NVR: Camect Status: Created
   Camect Warning                  Camect NVR: Restarting Device, error: [Errno 8] nodename nor servname provided, or not known
   Camect Debug                    Camect NVR: Camect Status: Disconnected
   Camect Error                    Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1278, in deviceUpdated
  File "plugin.py", line 67, in deviceStartComm
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/Plugins/Camect.indigoPlugin/Contents/Server Plugin/camect.py", line 86, in get_info
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 71, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='camect.local', port=443): Max retries exceeded with url: /api/GetHomeInfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x119c19c50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

   Camect                          Camect NVR: Stopping Device
   Camect                          Camect NVR: Starting Device
   Camect Debug                    Camect NVR: Camect Status: Created
   Camect Warning                  Camect NVR: Restarting Device, error: [Errno 8] nodename nor servname provided, or not known
   Camect Debug                    Camect NVR: Camect Status: Disconnected
   Camect Error                    Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1278, in deviceUpdated
  File "plugin.py", line 67, in deviceStartComm
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/Plugins/Camect.indigoPlugin/Contents/Server Plugin/camect.py", line 86, in get_info
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 71, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='camect.local', port=443): Max retries exceeded with url: /api/GetHomeInfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x119c19990>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

   Camect                          Camect NVR: Stopping Device
   Camect                          Camect NVR: Starting Device
   Camect Debug                    Camect NVR: Camect Status: Created
   Camect Warning                  Camect NVR: Restarting Device, error: [Errno 8] nodename nor servname provided, or not known
   Camect Debug                    Camect NVR: Camect Status: Disconnected
   Camect Error                    Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1278, in deviceUpdated
  File "plugin.py", line 67, in deviceStartComm
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/Plugins/Camect.indigoPlugin/Contents/Server Plugin/camect.py", line 86, in get_info
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 71, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='camect.local', port=443): Max retries exceeded with url: /api/GetHomeInfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x119c26310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

   Camect                          Camect NVR: Stopping Device
   Camect                          Camect NVR: Starting Device
   Camect Debug                    Camect NVR: Camect Status: Created
   Camect Warning                  Camect NVR: Restarting Device, error: [Errno 8] nodename nor servname provided, or not known
   Camect Debug                    Camect NVR: Camect Status: Disconnected
   Camect Error                    Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1278, in deviceUpdated
  File "plugin.py", line 67, in deviceStartComm
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/Plugins/Camect.indigoPlugin/Contents/Server Plugin/camect.py", line 86, in get_info
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 71, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='camect.local', port=443): Max retries exceeded with url: /api/GetHomeInfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x119c26350>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

   Camect                          Camect NVR: Stopping Device
   Camect                          Camect NVR: Starting Device
   Camect Debug                    Camect NVR: Camect Status: Created
   Camect Warning                  Camect NVR: Restarting Device, error: [Errno 8] nodename nor servname provided, or not known
   Camect Debug                    Camect NVR: Camect Status: Disconnected
   Camect Error                    Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1278, in deviceUpdated
  File "plugin.py", line 67, in deviceStartComm
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/Plugins/Camect.indigoPlugin/Contents/Server Plugin/camect.py", line 86, in get_info
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 71, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='camect.local', port=443): Max retries exceeded with url: /api/GetHomeInfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x119c266d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

   Camect                          Camect NVR: Stopping Device
   Camect                          Camect NVR: Starting Device
   Camect Debug                    Camect NVR: Camect Status: Created
   Camect Warning                  Camect NVR: Restarting Device, error: [Errno 8] nodename nor servname provided, or not known
   Camect Debug                    Camect NVR: Camect Status: Disconnected
   Camect Error                    Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1278, in deviceUpdated
  File "plugin.py", line 67, in deviceStartComm
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/Plugins/Camect.indigoPlugin/Contents/Server Plugin/camect.py", line 86, in get_info
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 71, in get
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='camect.local', port=443): Max retries exceeded with url: /api/GetHomeInfo (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x119c26910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

   Camect                          Camect NVR: Stopping Device
   Camect                          Camect NVR: Starting Device
   Camect Debug                    Camect NVR: Camect Status: Created
   Camect Debug                    Camect NVR: Camect Status: Connected
```

**Comment by FlyingDiver** [comment]
I have not seen this in a long time.  Closing unless I can reproduce.
