### ISSUE TITLE
'IndigoLogger' object has no attribute 'theaddebug'

### ISSUE THREAD

**Issue by DifferentComputers** [FlyingDiver/Indigo-Camect#8]
`Camect Error                    Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 283, in snapshotCameraCommand
  File "/Library/Application Support/Perceptive Automation/Indigo 2021.1/Plugins/Camect.indigoPlugin/Contents/Server Plugin/camect.py", line 115, in snapshot_camera
  File "plugin.py", line 105, in callBack
AttributeError: 'IndigoLogger' object has no attribute 'theaddebug'
`

**Comment by DifferentComputers** [comment]
Was wondering why some of my snapshots weren't posting to my "Alert" control page, and when I manually trigger one, this is what I see.

Running 0.0.7 and this used to work. Haven't made any substantive changes to my Indigo setup in months. Just stuff like new automations, added some bulbs.

**Comment by FlyingDiver** [comment]
This was fixed in 0.0.8.
